# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trans.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='trans.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0btrans.proto\"\'\n\tkey_value\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"N\n\ninsertMess\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\x12\x10\n\x08\x64\x61tabase\x18\x02 \x01(\t\x12\r\n\x05table\x18\x03 \x01(\t\x12\x0e\n\x06values\x18\x04 \x03(\t\"e\n\x12insertMessWithAttr\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\x12\x10\n\x08\x64\x61tabase\x18\x02 \x01(\t\x12\r\n\x05table\x18\x03 \x01(\t\x12\x1d\n\tattribute\x18\x04 \x03(\x0b\x32\n.key_value\"9\n\tcondition\x12\x0c\n\x04left\x18\x01 \x01(\t\x12\x0f\n\x07operand\x18\x02 \x01(\t\x12\r\n\x05right\x18\x03 \x01(\t\"2\n\x05where\x12\x1a\n\x06limits\x18\x01 \x03(\x0b\x32\n.condition\x12\r\n\x05logic\x18\x02 \x03(\t\"t\n\nupdateMess\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\x12\x10\n\x08\x64\x61tabase\x18\x02 \x01(\t\x12\r\n\x05table\x18\x03 \x01(\t\x12\x1d\n\tattribute\x18\x04 \x03(\x0b\x32\n.key_value\x12\x15\n\x05where\x18\x05 \x01(\x0b\x32\x06.where\"U\n\ndeleteMess\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\x12\x10\n\x08\x64\x61tabase\x18\x02 \x01(\t\x12\r\n\x05table\x18\x03 \x01(\t\x12\x15\n\x05where\x18\x04 \x01(\x0b\x32\x06.where\"T\n\x0f\x63reateTableMess\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\x12\x10\n\x08\x64\x61tabase\x18\x02 \x01(\t\x12\r\n\x05table\x18\x03 \x01(\t\x12\x0f\n\x07\x64\x65\x66ines\x18\x04 \x03(\t\"1\n\x0c\x63reateDBMess\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\x12\x10\n\x08\x64\x61tabase\x18\x02 \x01(\t\"A\n\rdropTableMess\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\x12\x10\n\x08\x64\x61tabase\x18\x02 \x01(\t\x12\r\n\x05table\x18\x03 \x01(\t\"/\n\ndropDBMess\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\x12\x10\n\x08\x64\x61tabase\x18\x02 \x01(\tb\x06proto3'
)




_KEY_VALUE = _descriptor.Descriptor(
  name='key_value',
  full_name='key_value',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='key_value.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='key_value.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=54,
)


_INSERTMESS = _descriptor.Descriptor(
  name='insertMess',
  full_name='insertMess',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='command', full_name='insertMess.command', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='database', full_name='insertMess.database', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='table', full_name='insertMess.table', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='values', full_name='insertMess.values', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=134,
)


_INSERTMESSWITHATTR = _descriptor.Descriptor(
  name='insertMessWithAttr',
  full_name='insertMessWithAttr',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='command', full_name='insertMessWithAttr.command', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='database', full_name='insertMessWithAttr.database', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='table', full_name='insertMessWithAttr.table', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='attribute', full_name='insertMessWithAttr.attribute', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=237,
)


_CONDITION = _descriptor.Descriptor(
  name='condition',
  full_name='condition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='left', full_name='condition.left', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='operand', full_name='condition.operand', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='right', full_name='condition.right', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=239,
  serialized_end=296,
)


_WHERE = _descriptor.Descriptor(
  name='where',
  full_name='where',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='limits', full_name='where.limits', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='logic', full_name='where.logic', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=298,
  serialized_end=348,
)


_UPDATEMESS = _descriptor.Descriptor(
  name='updateMess',
  full_name='updateMess',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='command', full_name='updateMess.command', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='database', full_name='updateMess.database', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='table', full_name='updateMess.table', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='attribute', full_name='updateMess.attribute', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='where', full_name='updateMess.where', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=350,
  serialized_end=466,
)


_DELETEMESS = _descriptor.Descriptor(
  name='deleteMess',
  full_name='deleteMess',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='command', full_name='deleteMess.command', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='database', full_name='deleteMess.database', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='table', full_name='deleteMess.table', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='where', full_name='deleteMess.where', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=468,
  serialized_end=553,
)


_CREATETABLEMESS = _descriptor.Descriptor(
  name='createTableMess',
  full_name='createTableMess',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='command', full_name='createTableMess.command', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='database', full_name='createTableMess.database', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='table', full_name='createTableMess.table', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='defines', full_name='createTableMess.defines', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=555,
  serialized_end=639,
)


_CREATEDBMESS = _descriptor.Descriptor(
  name='createDBMess',
  full_name='createDBMess',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='command', full_name='createDBMess.command', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='database', full_name='createDBMess.database', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=641,
  serialized_end=690,
)


_DROPTABLEMESS = _descriptor.Descriptor(
  name='dropTableMess',
  full_name='dropTableMess',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='command', full_name='dropTableMess.command', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='database', full_name='dropTableMess.database', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='table', full_name='dropTableMess.table', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=692,
  serialized_end=757,
)


_DROPDBMESS = _descriptor.Descriptor(
  name='dropDBMess',
  full_name='dropDBMess',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='command', full_name='dropDBMess.command', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='database', full_name='dropDBMess.database', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=759,
  serialized_end=806,
)

_INSERTMESSWITHATTR.fields_by_name['attribute'].message_type = _KEY_VALUE
_WHERE.fields_by_name['limits'].message_type = _CONDITION
_UPDATEMESS.fields_by_name['attribute'].message_type = _KEY_VALUE
_UPDATEMESS.fields_by_name['where'].message_type = _WHERE
_DELETEMESS.fields_by_name['where'].message_type = _WHERE
DESCRIPTOR.message_types_by_name['key_value'] = _KEY_VALUE
DESCRIPTOR.message_types_by_name['insertMess'] = _INSERTMESS
DESCRIPTOR.message_types_by_name['insertMessWithAttr'] = _INSERTMESSWITHATTR
DESCRIPTOR.message_types_by_name['condition'] = _CONDITION
DESCRIPTOR.message_types_by_name['where'] = _WHERE
DESCRIPTOR.message_types_by_name['updateMess'] = _UPDATEMESS
DESCRIPTOR.message_types_by_name['deleteMess'] = _DELETEMESS
DESCRIPTOR.message_types_by_name['createTableMess'] = _CREATETABLEMESS
DESCRIPTOR.message_types_by_name['createDBMess'] = _CREATEDBMESS
DESCRIPTOR.message_types_by_name['dropTableMess'] = _DROPTABLEMESS
DESCRIPTOR.message_types_by_name['dropDBMess'] = _DROPDBMESS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

key_value = _reflection.GeneratedProtocolMessageType('key_value', (_message.Message,), {
  'DESCRIPTOR' : _KEY_VALUE,
  '__module__' : 'trans_pb2'
  # @@protoc_insertion_point(class_scope:key_value)
  })
_sym_db.RegisterMessage(key_value)

insertMess = _reflection.GeneratedProtocolMessageType('insertMess', (_message.Message,), {
  'DESCRIPTOR' : _INSERTMESS,
  '__module__' : 'trans_pb2'
  # @@protoc_insertion_point(class_scope:insertMess)
  })
_sym_db.RegisterMessage(insertMess)

insertMessWithAttr = _reflection.GeneratedProtocolMessageType('insertMessWithAttr', (_message.Message,), {
  'DESCRIPTOR' : _INSERTMESSWITHATTR,
  '__module__' : 'trans_pb2'
  # @@protoc_insertion_point(class_scope:insertMessWithAttr)
  })
_sym_db.RegisterMessage(insertMessWithAttr)

condition = _reflection.GeneratedProtocolMessageType('condition', (_message.Message,), {
  'DESCRIPTOR' : _CONDITION,
  '__module__' : 'trans_pb2'
  # @@protoc_insertion_point(class_scope:condition)
  })
_sym_db.RegisterMessage(condition)

where = _reflection.GeneratedProtocolMessageType('where', (_message.Message,), {
  'DESCRIPTOR' : _WHERE,
  '__module__' : 'trans_pb2'
  # @@protoc_insertion_point(class_scope:where)
  })
_sym_db.RegisterMessage(where)

updateMess = _reflection.GeneratedProtocolMessageType('updateMess', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEMESS,
  '__module__' : 'trans_pb2'
  # @@protoc_insertion_point(class_scope:updateMess)
  })
_sym_db.RegisterMessage(updateMess)

deleteMess = _reflection.GeneratedProtocolMessageType('deleteMess', (_message.Message,), {
  'DESCRIPTOR' : _DELETEMESS,
  '__module__' : 'trans_pb2'
  # @@protoc_insertion_point(class_scope:deleteMess)
  })
_sym_db.RegisterMessage(deleteMess)

createTableMess = _reflection.GeneratedProtocolMessageType('createTableMess', (_message.Message,), {
  'DESCRIPTOR' : _CREATETABLEMESS,
  '__module__' : 'trans_pb2'
  # @@protoc_insertion_point(class_scope:createTableMess)
  })
_sym_db.RegisterMessage(createTableMess)

createDBMess = _reflection.GeneratedProtocolMessageType('createDBMess', (_message.Message,), {
  'DESCRIPTOR' : _CREATEDBMESS,
  '__module__' : 'trans_pb2'
  # @@protoc_insertion_point(class_scope:createDBMess)
  })
_sym_db.RegisterMessage(createDBMess)

dropTableMess = _reflection.GeneratedProtocolMessageType('dropTableMess', (_message.Message,), {
  'DESCRIPTOR' : _DROPTABLEMESS,
  '__module__' : 'trans_pb2'
  # @@protoc_insertion_point(class_scope:dropTableMess)
  })
_sym_db.RegisterMessage(dropTableMess)

dropDBMess = _reflection.GeneratedProtocolMessageType('dropDBMess', (_message.Message,), {
  'DESCRIPTOR' : _DROPDBMESS,
  '__module__' : 'trans_pb2'
  # @@protoc_insertion_point(class_scope:dropDBMess)
  })
_sym_db.RegisterMessage(dropDBMess)


# @@protoc_insertion_point(module_scope)
